# Generated by Django 5.2.9 on 2026-01-15 02:21

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_viajes', '0002_posteo_autor_posteo_cuerpo_posteo_imagen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posteo',
            name='cuerpo',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
