# Generated by Django 5.2.9 on 2026-01-15 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_viajes', '0003_alter_posteo_cuerpo'),
    ]

    operations = [
        migrations.AddField(
            model_name='avatar',
            name='biografia',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='avatar',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='avatar',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
